# Define the Project's name
export PROJECT=MyAxiStreamModuleWrapper

# Define Firmware Version: v1.2.3.4
export PRJ_VERSION=0x01020304

# Using the common Makefile build configuration
include ../shared_build_config.mk
